name: smart-contracts CD dev

on:
  push:
    branches:
    - main

defaults:
  run:
    working-directory: smart-contracts

jobs:
  test:
    uses: ./.github/workflows/smart-contracts-ci.yml

  publish-dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: publish
        run: ./scripts/publish-dev.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
